call plug#begin('~/.vim/plugged')

" Tree-like panel to navigate files
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }

" Commenting
Plug 'tpope/vim-commentary'

" Linter
Plug 'w0rp/ale'

" Git-related
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rhubarb'
Plug 'shumphrey/fugitive-gitlab.vim'

" Filetype helpers
Plug 'hashivim/vim-terraform'  , {'for': 'terraform'}
Plug 'pearofducks/ansible-vim' , {'for': 'ansible*'}

" Snippets
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'

" Fuzzy finder
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'

call plug#end()

syntax on
filetype plugin indent on

" Colors
colorscheme desert
set bg=light

" Display
set relativenumber
set nowrap
set laststatus=2
set scrolloff=3
set colorcolumn=81

" Misc
set nocompatible
set mouse+=a
set hidden
set wildmenu
set diffopt+=vertical

" Indentation and tab key handling
set tabstop=2 shiftwidth=2 softtabstop=2
set smarttab
set expandtab
set autoindent
set smartindent

" Search related
set ignorecase
set smartcase
set incsearch
set hlsearch

" Files
set backup
set undofile
set directory=~/.vim/vimswap//
set backupdir=~/.vim/vimbackup//
set undodir=~/.vim/vimundo//
set viminfo+=n~/.vim/misc/viminfo

" Wildmenu
set wildignorecase
set wildignore+=*.pyc,*.retry

" Speed up grep
" set grepprg=ag\ --vimgrep\ $*

let g:UltiSnipsExpandTrigger = "<c-j>"
let g:UltiSnipsListSnippets = "<tab>"

